# Generated by Django 4.2.24 on 2025-12-30 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="color",
            field=models.CharField(default="blue", max_length=20),
        ),
        migrations.AddField(
            model_name="agent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="icon",
            field=models.CharField(default="💬", max_length=50),
        ),
        migrations.AddField(
            model_name="agent",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
    ]
