# Generated by Django 4.2.24 on 2025-12-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_agent_color_agent_created_by_agent_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="color",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="icon",
        ),
    ]
